Improve Docker Push workflow and Dockerfiles

diff --git a/.github/workflows/docker-push.yml b/.github/workflows/docker-push.yml
--- a/.github/workflows/docker-push.yml
+++ b/.github/workflows/docker-push.yml
@@ -3,6 +3,13 @@ name: "Docker Push"
 on:
   release:
     types: [published]
+  workflow_dispatch:
+    inputs:
+      force_rebuild:
+        description: 'Force container rebuild'
+        required: true
+        type: choice
+        options: [yes, no]
   schedule:
     - cron: '30 12 * * *'
 
@@ -20,7 +27,7 @@ jobs:
 
     strategy:
       matrix:
-        tag: [ 'centos7', 'micro' ]
+        image: [ 'centos7', 'micro' ]
 
     steps:
       - name: Checkout
@@ -67,17 +74,17 @@ jobs:
             exit 1
           fi
 
-          docker_file=".docker/${{matrix.tag}}.docker"
-          base_image=$(grep 'FROM ' $docker_file | tail -1 | cut -f2 -d' ')
+          docker_file=".docker/${{matrix.image}}.docker"
+          base_image=$(grep 'FROM ' $docker_file | grep -v 'builder' | sed 's#${REGISTRY}/##' | tail -1 | cut -f2 -d' ')
 
           if [[ -z "$base_image" ]] ; then
             echo "::error::Can't extract base image info"
             exit 1
           fi
 
-          echo "::set-output name=version::$version"
-          echo "::set-output name=dockerfile::$docker_file"
-          echo "::set-output name=baseimage::$base_image"
+          echo "version=$version" >> $GITHUB_OUTPUT
+          echo "dockerfile=$docker_file" >> $GITHUB_OUTPUT
+          echo "baseimage=$base_image" >> $GITHUB_OUTPUT
 
           echo -e "\033[34mVersion:\033[0m    $version"
           echo -e "\033[34mDockerfile:\033[0m $docker_file"
@@ -87,14 +94,20 @@ jobs:
         id: build_check
         run: |
           if [[ "${{github.event_name}}" == "release" ]] ; then
-            echo "::set-output name=build::true"
+            echo "build=true" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+
+          if [[ "${{ github.event.inputs.force_rebuild }}" == "true" ]] ; then
+            echo "::warning::Rebuild ${{matrix.version}} (reason: forced rebuild)"
+            echo "build=true" >> $GITHUB_OUTPUT
             exit 0
           fi
 
           echo -e "::group::\033[34mDownloading built image…\033[0m"
 
-          if ! docker pull ghcr.io/${{env.IMAGE_NAME}}:${{matrix.tag}} ; then
-            echo "::error::Can't download image ${{env.IMAGE_NAME}}:${{matrix.tag}}"
+          if ! docker pull ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}} ; then
+            echo "::error::Can't download image ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}"
             exit 1
           fi
 
@@ -115,27 +128,41 @@ jobs:
             exit 1
           fi
 
-          if ! docker inspect "ghcr.io/${{env.IMAGE_NAME}}:${{matrix.tag}}" | jq -r '.[0].RootFS.Layers' | grep -q "$base_layer" ; then
+          if ! docker inspect "ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}" | jq -r '.[0].RootFS.Layers' | grep -q "$base_layer" ; then
             echo "::warning::Rebuild image (reason: base image rebuilt)"
-            echo "::set-output name=build::true"
+            echo "build=true" >> $GITHUB_OUTPUT
             exit 0
           fi
 
-      - name: Build and push Docker image
+      - name: Build and push Docker images (Docker)
         if: ${{ steps.build_check.outputs.build == 'true' }}
         uses: docker/build-push-action@v3
         with:
           push: true
           context: .
           file: ${{steps.metadata.outputs.dockerfile}}
+          build-args: |
+            REGISTRY=docker.io
           tags: |
-            ghcr.io/${{env.IMAGE_NAME}}:${{matrix.tag}}-${{steps.metadata.outputs.version}}
-            ghcr.io/${{env.IMAGE_NAME}}:${{matrix.tag}}
-            ${{env.IMAGE_NAME}}:${{matrix.tag}}-${{steps.metadata.outputs.version}}
-            ${{env.IMAGE_NAME}}:${{matrix.tag}}
+            ${{env.IMAGE_NAME}}:${{matrix.image}}-${{steps.metadata.outputs.version}}
+            ${{env.IMAGE_NAME}}:${{matrix.image}}
+
+      - name: Build and push Docker images (GHCR)
+        if: ${{ steps.build_check.outputs.build == 'true' }}
+        uses: docker/build-push-action@v3
+        with:
+          push: true
+          context: .
+          file: ${{steps.metadata.outputs.dockerfile}}
+          build-args: |
+            REGISTRY=ghcr.io
+          tags: |
+            ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}-${{steps.metadata.outputs.version}}
+            ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}
 
       - name: Show info about built Docker image
+        if: ${{ steps.build_check.outputs.build == 'true' }}
         uses: essentialkaos/docker-info-action@v1
         with:
-          image: ghcr.io/${{env.IMAGE_NAME}}:${{matrix.tag}}
+          image: ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}
           show-labels: true
